# Generated by Django 3.2.1 on 2021-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('image', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
