# Generated by Django 3.2.1 on 2021-07-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='success',
            field=models.BooleanField(default=0),
        ),
    ]
