# Generated by Django 3.2.1 on 2021-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='description',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threat',
            name='image',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
