# Generated by Django 3.2.1 on 2021-05-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_auto_20210506_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
