# Generated by Django 3.2.1 on 2021-05-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0003_threat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
