# Generated by Django 3.2.1 on 2021-05-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0004_alter_threat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
