# Generated by Django 3.2.1 on 2021-05-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [

    ]
