# Generated by Django 3.2.1 on 2021-05-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20210505_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
