# Generated by Django 3.2.1 on 2021-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_rename_user_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='token',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
